ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.infra.ApplicationKt.module ]
    }
    storage {
        jdbcUrl = "jdbc:sqlite:data/infra-control.db"
    }
}
